name: Run Batch Process Every 1 Minute (Main Branch)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:

jobs:
  batch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
          
      - name: Run batch process
        run: |
          curl -f -X POST https://youtube-blog-ai.vercel.app/api/batch/generate-articles -H "Content-Type: application/json" -d '{"apiKey": "${{ secrets.API_KEY }}", "limit": 15}'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
